// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.Robert.subsystems;

import org.usfirst.frc841.Robert.RobotMap;
import org.usfirst.frc841.Robert.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Intakes extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController intakeDrive1 = RobotMap.intakesIntakeDrive1;
    SpeedController intakeDrive2 = RobotMap.intakesIntakeDrive2;
    DoubleSolenoid intakeGrabber = RobotMap.intakesIntakeGrabber;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void pullInMotor() {
    	intakeDrive1.set(1);
    	intakeDrive2.set(-1);
    }
    public void spitOutMotor() {
    	intakeDrive1.set(-1);
    	intakeDrive2.set(1);
    	
    }
    public void stopIntakeMotor() {
    	intakeDrive1.set(0);
    	intakeDrive2.set(0);
    }
    public void openIntakes() {
    	intakeGrabber.set(DoubleSolenoid.Value.kForward);
    }
    public void closeIntakes() {
    	intakeGrabber.set(DoubleSolenoid.Value.kReverse);
    }
}

