// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.Robert;

import org.usfirst.frc841.Robert.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton setQuickTurn6;
    public JoystickButton stopQuickTurn6;
    public Joystick driver;
    public JoystickButton bringInTote6;
    public JoystickButton openIntakes8;
    public JoystickButton spitOutTote5;
    public JoystickButton closeIntakes7;
    public Joystick coDriver;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        coDriver = new Joystick(1);
        
        closeIntakes7 = new JoystickButton(coDriver, 7);
        closeIntakes7.whileHeld(new HoldTote());
        spitOutTote5 = new JoystickButton(coDriver, 5);
        spitOutTote5.whileHeld(new SpitOutTote());
        openIntakes8 = new JoystickButton(coDriver, 8);
        openIntakes8.whileHeld(new ReleaseTote());
        bringInTote6 = new JoystickButton(coDriver, 6);
        bringInTote6.whileHeld(new BringInTote());
        driver = new Joystick(0);
        
        stopQuickTurn6 = new JoystickButton(driver, 6);
        stopQuickTurn6.whenReleased(new StopQuickTurn());
        setQuickTurn6 = new JoystickButton(driver, 6);
        setQuickTurn6.whenPressed(new SetQuickTurn());

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("PickUpTote", new PickUpTote());

        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        SmartDashboard.putData("Drive", new Drive());

        SmartDashboard.putData("SetQuickTurn", new SetQuickTurn());

        SmartDashboard.putData("StopQuickTurn", new StopQuickTurn());

        SmartDashboard.putData("BringInTote", new BringInTote());

        SmartDashboard.putData("SpitOutTote", new SpitOutTote());

        SmartDashboard.putData("ReleaseTote", new ReleaseTote());

        SmartDashboard.putData("HoldTote", new HoldTote());

        SmartDashboard.putData("ElevatorSetpoint", new ElevatorSetpoint());

        SmartDashboard.putData("PlaceStackDown", new PlaceStackDown());

        SmartDashboard.putData("SetElevatorAngle", new SetElevatorAngle());

        SmartDashboard.putData("OpenPincer", new OpenPincer());

        SmartDashboard.putData("ClosePincer", new ClosePincer());

        SmartDashboard.putData("SetClawAngle", new SetClawAngle());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        SmartDashboard.putData("SetElevatorHeight", new SetElevatorHeight(2));
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriver() {
        return driver;
    }

    public Joystick getCoDriver() {
        return coDriver;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

